[project]
name = "adaptive-streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "os-ken>=3.1.1",
    "pyzmq>=27.1.0",
]
